import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreModalProvider from "@/providers/store-modal-provider";
import DeleteModalProvider from "@/providers/delete-modal-provider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreModalProvider />
      <DeleteModalProvider />
      <body className={inter.className}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
